### PR TITLE
Switch to speakeasy-api/jsonpath

### LINKED ISSUE #49: Inconsistent results with recursive descent with filter expression
In the repo we have a sample deck file: `docs/summertime-kong.yml` that has one service and one route and the route is defined under the service.

Applying a patch with a selector that uses recursive descent and a filter expression results in (I believe) inconsistent results:

The first example's selector is explicit in the path to the routes:
```
> kced patch -s docs/summertime-kong.yml --selector '$.services[*].routes[?(@.name=="summer-time_get")]' --value 'field:"foo"'
_format_version: "3.0"
services:
- host: mockbin.org
  id: b1525aee-d304-11ed-afa1-0242ac120002
  name: summer-time
  path: /requests
  plugins: []
  port: 443
  protocol: https
  routes:
  - field: foo
    id: b7d87736-d304-11ed-afa1-0242ac120002
    methods:
    - GET
    name: summer-time_get
    paths:
    - ~/summer-time$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags: []
```

In the second example we use recursive descent which should result in the same behavior, but do not get the expected results:
```
❯ kced patch -s docs/summertime-kong.yml --selector '$..routes[?(@.name=="summer-time_get")]' --value 'field:"foo"'
_format_version: "3.0"
services:
- host: mockbin.org
  id: b1525aee-d304-11ed-afa1-0242ac120002
  name: summer-time
  path: /requests
  plugins: []
  port: 443
  protocol: https
  routes:
  - id: b7d87736-d304-11ed-afa1-0242ac120002
    methods:
    - GET
    name: summer-time_get
    paths:
    - ~/summer-time$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags: []
```

Using https://jsonpath.com/ to validate, I see the following:

Screenshot 2023-04-21 at 9 52 28 AM

Screenshot 2023-04-21 at 9 52 37 AM

### LINKED ISSUE #218: Conditional logic for JSONPath selectors not working
When applying conditional logic for a plugin using `deck file add-plugins`, only the first piece of logic is matched and applied.

Using the command

`cat ./kong-simple-config.json | deck file add-plugins --format json ./get-post-route-plugins.yaml`

Plugins are only applied to GET routes not POST routes, the selectors JSONPath is

`$.services[*].routes[?(@.methods[?(@=='GET' ) || (@=='POST')])]`

[get-post-route-plugins.yaml.txt](https://github.com/user-attachments/files/17507711/get-post-route-plugins.yaml.txt)
[get-route-plugins.yaml.txt](https://github.com/user-attachments/files/17507687/get-route-plugins.yaml.txt)
[kong-simple-config.json](https://github.com/user-attachments/files/17507567/kong-simple-config.json)

### PR DESCRIPTION
**Pull request by mheap**
The newly added tests failed at e3b8a44406290d0354cd0fa45e37f7e6d4b3daa9, and passed at 37fc94737b84db809a083cbde5dcc3f6b802b120

All existing tests continue to pass, and the failing tests I added to reproduce the issue are also passing

Resolves #49 
Resolves #218

### CODE REVIEW

File: patch/deckpatch.go [hunk 1]
```diff
@@ -170,15 +170,11 @@ func (patch *DeckPatch) ApplyToNodes(yamlData *yaml.Node) (err error) {
 
 	// query the yamlData using the selector
 	nodes := make([]*yaml.Node, 0)
-	for _, selector := range patch.Selectors {
-		moreNodes, err := selector.Find(yamlData)
```
Comment (harshadixit12) [inline patch/deckpatch.go:174]: Verified that it is safe to do this - selector.Find never returned errors in the old library https://github.com/vmware-labs/yaml-jsonpath/blob/v0.3.2/pkg/yamlpath/path.go#L24

**Review by harshadixit12 — APPROVED** [review]

**Comment by harshadixit12** [comment]
> @harshadixit12 Can I leave it with you to do a release of go-apiops and update deck?

Yes, i'll get it done sometime this week.

File: go.mod [hunk 2]
```diff
@@ -12,10 +12,10 @@ require (
 	github.com/kong/go-slugify v1.0.0
 	github.com/onsi/ginkgo/v2 v2.22.2
 	github.com/onsi/gomega v1.36.2
-	github.com/pb33f/libopenapi v0.16.13
+	github.com/pb33f/libopenapi v0.24.0
```
Comment (harshadixit12) [inline go.mod:15]: @mheap this is not necessary for speakeasy jsonpath, correct? 
This breaks vacuum on deck, i'll downgrade it to 0.23.0 (which is required by vacuum), and bump vacuum version in deck together.
